### ISSUE TITLE
Commit issue: Pop up only comes up when both users swipe right

### ISSUE THREAD

**Issue by ahnafnafee** [ahnafnafee/RoomiePrototype#25]
Link: https://github.com/ahnafnafee/RoomiePrototype/commit/f63d9c902bdee3e6c9181822efc0c89fce88a62e

This commit is causing weird null pointer error in CardStack. Could you look into it?

**Comment by Saharshv** [comment]
Can you tell me the exact line?

**Comment by ahnafnafee** [comment]
All the code points which concerned swipeRightBy

**Comment by Saharshv** [comment]
It's just an ArrayList

**Comment by Saharshv** [comment]
It's not causing any problem till my last commit
