### ISSUE TITLE
User Detail infalter bug

### ISSUE THREAD

**Issue by ahnafnafee** [ahnafnafee/RoomiePrototype#28]
Unknown bug while inflating user details. Happens only for certain users for some unknown reason. Tried resetting database but bug persists.

**Comment by Saharshv** [comment]
It crashes only when the user taps on someone who has already swiped right on them

**Comment by Saharshv** [comment]
> It crashes only when the user taps on someone who has already swiped right on them

Nope, it's random

**Comment by ahnafnafee** [comment]
> 
> 
> > It crashes only when the user taps on someone who has already swiped right on them
> 
> Nope, it's random

Okay, I think I might have found the error. Let me see if i can resolve this.

**Comment by Saharshv** [comment]
> > > It crashes only when the user taps on someone who has already swiped right on them
> > 
> > 
> > Nope, it's random
> 
> Okay, I think I might have found the error. Let me see if i can resolve this.

Okay, let me know what it was

**Comment by Saharshv** [comment]
Okay, I think even I found the bug

**Comment by ahnafnafee** [comment]
> 
> 
> Okay, I think even I found the bug

I fixed it XD

**Comment by ahnafnafee** [comment]
I'm gonna push the code to master.

**Comment by Saharshv** [comment]
It was because of the transaction size too big right?

**Comment by Saharshv** [comment]
> I'm gonna push the code to master.

Okay

**Comment by ahnafnafee** [comment]
> 
> 
> It was because of the transaction size too big right?

Yeah, the java binding error. I thought that if converted it to byte code, it would work but the size was still too big. A possible solution was to cache the image but I don't understand the code for that.

Caching: https://stackoverflow.com/questions/31131640/android-java-binder-failed-binder-transaction
